version: "3"

services:
  qbittorrent:
    container_name: qbittorrent
    image: nevinee/qbittorrent:${QBITTORRENT_VERSION:-latest}
    restart: always
    network_mode: bridge
    ports:
      - ${QBITTORRENT_BT_PORT:-6881}:${QBITTORRENT_BT_PORT:-6881}
      - ${QBITTORRENT_BT_PORT:-6881}:${QBITTORRENT_BT_PORT:-6881}/udp
    environment:
      - PUID=0
      - PGID=0
      - TZ=${QBITTORRENT_TIMEZONE:-Etc/UTC}
      - BT_PORT=${QBITTORRENT_BT_PORT:-6881}
      - WEBUI_PORT=8080
    volumes:
      - ${QBITTORRENT_DATA_PATH:-data}:/data
      - ${QBITTORRENT_DOWNLOAD_PATH:-./media/downloads}:/media/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.rule: Host(`${QBITTORRENT_HOST:-qbittorrent.example.com}`)
      traefik.http.routers.qbittorrent.tls.certresolver: default
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.services.qbittorrent.loadbalancer.passhostheader: false

volumes:
  data:
