version: "3"

services:
  qbittorrent:
    container_name: qbittorrent
    image: nevinee/qbittorrent:${QBITTORRENT_VERSION:-latest}
    restart: always
    network_mode: host
    ports:
      - ${QBITTORRENT_BT_PORT:-6881}:${QBITTORRENT_BT_PORT:-6881}
      - ${QBITTORRENT_BT_PORT:-6881}:${QBITTORRENT_BT_PORT:-6881}/udp
      - ${QBITTORRENT_WEBUI_PORT:-8085}:${QBITTORRENT_WEBUI_PORT:-8085}
    environment:
      - PUID=0
      - PGID=0
      - TZ=${QBITTORRENT_TIMEZONE:-Etc/UTC}
      - BT_PORT=${QBITTORRENT_BT_PORT:-6881}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT:-8085}
      - QB_USERNAME=${QBITTORRENT_USERNAME:-admin}
      - QB_PASSWORD=${QBITTORRENT_PASSWORD:-adminadmin}
    volumes:
      - ${QBITTORRENT_DATA_PATH:-./data}:/data
      - ${QBITTORRENT_DOWNLOAD_PATH:-./media/downloads}:/media/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.rule: Host(`${QBITTORRENT_HOST:-qb.example.com}`)
      traefik.http.routers.qbittorrent.tls.certresolver: default
      traefik.http.services.qbittorrent.loadbalancer.server.port: ${QBITTORRENT_WEBUI_PORT:-8085}
      traefik.http.services.qbittorrent.loadbalancer.passhostheader: false
