version: "3"

services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:${N8N_VERSION:-latest}
    restart: always
    network_mode: bridge
    volumes:
      - ${N8N_DATA_PATH:-./data}:/home/node/.n8n
    environment:
      TZ: ${TZ:-UTC}
      GENERIC_TIMEZONE: ${TZ:-UTC}
      WEBHOOK_URL: https://${N8N_HOST:-n8n.example.com}/
    labels:
      traefik.enable: true
      traefik.http.routers.n8n.entrypoints: websecure
      traefik.http.routers.n8n.rule: Host(`${N8N_HOST:-n8n.example.com}`)
      traefik.http.routers.n8n.tls.certresolver: default
