version: "3"

services:
  cookiecloud:
    container_name: cookiecloud
    image: easychen/cookiecloud:${COOKIECLOUD_VERSION:-latest}
    restart: always
    network_mode: bridge
    ports:
      - ${COOKIECLOUD_PORT:-8088}:8088
    labels:
      traefik.enable: true
      traefik.http.routers.cookiecloud.entrypoints: websecure
      traefik.http.routers.cookiecloud.rule: Host(`${COOKIECLOUD_HOST:-cookiecloud.example.com}`)
      traefik.http.routers.cookiecloud.tls.certresolver: default
