version: "3"

services:
  cookiecloud:
    container_name: cookiecloud
    image: easychen/cookiecloud:${COOKIECLOUD_VERSION:-latest}
    restart: always
    network_mode: bridge
    environment:
      WEBHOOK_URL: https://${COOKIECLOUD_HOST:-cookiecloud.example.com}/
    labels:
      traefik.enable: true
      traefik.http.routers.cookiecloud.entrypoints: websecure
      traefik.http.routers.cookiecloud.rule: Host(`${COOKIECLOUD_HOST:-cookiecloud.example.com}`)
      traefik.http.routers.cookiecloud.tls.certresolver: default
