version: "3"

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:${VAULTWARDEN_VERSION:-latest}
    restart: always
    network_mode: bridge
    volumes:
      - ${VAULTWARDEN_DATA_PATH:-data}:/data
    environment:
      - SIGNUPS_ALLOWED=${VAULTWARDEN_SIGNUPS_ALLOWED:-false}
      - INVITATIONS_ALLOWED=${VAULTWARDEN_INVITATIONS_ALLOWED:-true}
      - DOMAIN=${VAULTWARDEN_PROTOCOL:-http}://${VAULTWARDEN_HOST:-vault.example.com}
      - SMTP_FROM=${SMTP_FROM:-mailer@example.com}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Vaultwarden}
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.rule: Host(`${VAULTWARDEN_HOST:-vault.example.com}`)
      traefik.http.routers.vaultwarden.tls.certresolver: default

volumes:
  data:
