version: "3"

services:
  nas-tools:
    container_name: nas-tools
    image: nastool/nas-tools:${NAS_TOOLS_VERSION:-latest}
    restart: always
    network_mode: bridge
    volumes:
      - ${NAS_TOOLS_CONFIG_PATH:-nas-tools_config}:/config
      - ${NAS_TOOLS_MEDIA_PATH:-./media}:/media
    environment:
      - PUID=0
      - PGID=0
    labels:
      traefik.enable: true
      traefik.http.routers.nas-tools.entrypoints: websecure
      traefik.http.routers.nas-tools.rule: Host(`${NAS_TOOLS_HOST:-nas-tools.example.com}`)
      traefik.http.routers.nas-tools.tls.certresolver: default

  emby:
    container_name: emby
    image: emby/embyserver:${EMBY_VERSION:-latest}
    network_mode: host
    restart: always
    environment:
      - UID=0
      - GID=0
    volumes:
      - ${EMBY_CONFIG_PATH:-emby_config}:/config
      - ${EMBY_LIBRARY_PATH:-./media/libraries}:/media/libraries
    devices:
      - /dev/dri:/dev/dri
    labels:
      traefik.enable: true
      traefik.http.routers.emby.entrypoints: websecure
      traefik.http.routers.emby.rule: Host(`${EMBY_HOST:-emby.example.com}`)
      traefik.http.routers.emby.tls.certresolver: default
      traefik.http.services.emby.loadbalancer.server.port: 8096

  qbittorrent:
    container_name: qbittorrent
    image: nevinee/qbittorrent:${QBITTORRENT_VERSION:-latest}
    restart: always
    network_mode: bridge
    ports:
      - ${QBITTORRENT_WEBUI_PORT:-8080}:${QBITTORRENT_WEBUI_PORT:-8080}
      - ${QBITTORRENT_BT_PORT:-6881}:${QBITTORRENT_BT_PORT:-6881}
      - ${QBITTORRENT_BT_PORT:-6881}:${QBITTORRENT_BT_PORT:-6881}/udp
    environment:
      - PUID=0
      - PGID=0
      - TZ=${QBITTORRENT_TIMEZONE:-Etc/UTC}
      - BT_PORT=${QBITTORRENT_BT_PORT:-6881}
      - WEBUI_PORT=${QBITTORRENT_WEBUI_PORT:-8080}
    volumes:
      - ${QBITTORRENT_DATA_PATH:-qbittorrent_data}:/data
      - ${QBITTORRENT_DOWNLOAD_PATH:-./media/downloads}:/media/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.rule: Host(`${QBITTORRENT_HOST:-qbittorrent.example.com}`)
      traefik.http.routers.qbittorrent.tls.certresolver: default
      traefik.http.services.qbittorrent.loadbalancer.server.port: ${QBITTORRENT_WEBUI_PORT:-8080}
      traefik.http.services.qbittorrent.loadbalancer.passhostheader: false

volumes:
  nas-tools_config:
  emby_config:
  qbittorrent_data:
