version: "3"

services:
  moviepilot:
    container_name: moviepilot
    image: jxxghp/moviepilot:${MOVIEPILOT_VERSION:-latest}
    restart: always
    network_mode: bridge
    volumes:
      - ${MOVIEPILOT_CONFIG_PATH:-./config}:/config
      - ${MOVIEPILOT_MEDIA_PATH:-./media}:/media
      - ${QBITTORRENT_TORRENT_PATH:-./qbittorrent/torrents}:/qbittorrent/torrents
    environment:
      - MOVIEPILOT_AUTO_UPDATE=false
      # 认证
      - AUTH_SITE=${AUTH_SITE:-iyuu}
      - IYUU_SIGN=${IYUU_SIGN}
      - HHCLUB_USERNAME=${HHCLUB_USERNAME}
      - HHCLUB_PASSKEY=${HHCLUB_PASSKEY}
    labels:
      traefik.enable: true
      traefik.http.routers.moviepilot.entrypoints: websecure
      traefik.http.routers.moviepilot.rule: Host(`${MOVIEPILOT_HOST:-mp.example.com}`)
      traefik.http.routers.moviepilot.tls.certresolver: default
