version: "3"

services:
  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VERSION:-latest}
    restart: always
    network_mode: bridge
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --api.insecure=true
      # docker provider
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      # file provider
      - --providers.file.directory=/etc/traefik
      - --providers.file.watch=true
      # entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # certificate resolver
      - --certificatesResolvers.default.acme.dnsChallenge=true
      - --certificatesResolvers.default.acme.dnsChallenge.provider=cloudflare
      - --certificatesResolvers.default.acme.caServer=${TRAEFIK_ACME_CA_SERVER:-https://acme-staging-v02.api.letsencrypt.org/directory}
      - --certificatesResolvers.default.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesResolvers.default.acme.eab.kid=${TRAEFIK_ACME_EAB_KID:-}
      - --certificatesResolvers.default.acme.eab.hmacEncoded=${TRAEFIK_ACME_EAB_HMAC_KEY:-}
      - --certificatesresolvers.default.acme.storage=/certs/acme.json
    ports:
      - ${TRAEFIK_HTTP_PORT:-80}:80
      - ${TRAEFIK_HTTPS_PORT:-443}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_CONFIG_PATH:-./config}:/etc/traefik
      - ${TRAEFIK_CERTS_PATH:-./certs}:/certs
    environment:
      CF_DNS_API_TOKEN: ${TRAEFIK_CF_DNS_API_TOKEN}
    labels:
      # Global redirection: http to https
      traefik.http.routers.http-catchall.rule: HostRegexp(`{host:(www\.)?.+}`)
      traefik.http.routers.http-catchall.entrypoints: web
      traefik.http.routers.http-catchall.middlewares: www-to-https
      # Global redirection: https (www.) to https
      traefik.http.routers.https-catchall.tls: true
      traefik.http.routers.https-catchall.rule: HostRegexp(`{host:(www\.).+}`)
      traefik.http.routers.https-catchall.entrypoints: websecure
      traefik.http.routers.https-catchall.middlewares: www-to-https
      # middleware: http(s)://(www.) to  https://
      traefik.http.middlewares.www-to-https.redirectRegex.regex: ^https?://(?:www\.)?(.+)
      traefik.http.middlewares.www-to-https.redirectRegex.replacement: https://$${1}
      traefik.http.middlewares.www-to-https.redirectRegex.permanent: true
